# Generated by Django 3.2.8 on 2021-10-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_city', models.CharField(max_length=200)),
                ('second_city', models.CharField(max_length=200)),
                ('path', models.JSONField()),
            ],
        ),
    ]
