# Generated by Django 3.2.8 on 2021-11-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('point_x', models.FloatField()),
                ('point_y', models.FloatField()),
            ],
        ),
    ]
