# Generated by Django 3.2.8 on 2021-11-10 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_change_city_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_city_id', to='main.city')),
                ('second_city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_city_id', to='main.city')),
            ],
        ),
    ]
