# Generated by Django 3.2.8 on 2021-11-10 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_change_relation_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='first_city_id',
            new_name='first_city',
        ),
        migrations.RenameField(
            model_name='relation',
            old_name='second_city_id',
            new_name='second_city',
        ),
    ]
