# Generated by Django 3.2.8 on 2021-11-10 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_change_relation_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropsRelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('relation_type', models.CharField(max_length=200)),
                ('time', models.IntegerField()),
                ('cost', models.FloatField()),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.relation')),
            ],
        ),
    ]
