# Generated by Django 3.2.8 on 2021-12-05 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_create_props_relation_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityDebug',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('point_x', models.FloatField()),
                ('point_y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RouteDebug',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_city', models.CharField(max_length=200)),
                ('second_city', models.CharField(max_length=200)),
                ('path', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='RelationDebug',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_city', to='main.citydebug')),
                ('second_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_city', to='main.citydebug')),
            ],
        ),
        migrations.CreateModel(
            name='PropsRelationDebug',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('relation_type', models.CharField(max_length=200)),
                ('time', models.IntegerField()),
                ('cost', models.FloatField()),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.relationdebug')),
            ],
        ),
    ]
