# Generated by Django 3.2.8 on 2021-12-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_create_debug_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='propsrelation',
            name='schedule',
            field=models.JSONField(default='null'),
        ),
    ]
