# Generated by Django 3.2.8 on 2021-12-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_change_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='propsrelationdebug',
            name='schedule',
            field=models.JSONField(default='null'),
        ),
    ]
