# Generated by Django 3.2.8 on 2021-12-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_create_shedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='priority',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
